/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FileUpload } from "./FileUpload";
import { FileUploadCountArgs } from "./FileUploadCountArgs";
import { FileUploadFindManyArgs } from "./FileUploadFindManyArgs";
import { FileUploadFindUniqueArgs } from "./FileUploadFindUniqueArgs";
import { CreateFileUploadArgs } from "./CreateFileUploadArgs";
import { UpdateFileUploadArgs } from "./UpdateFileUploadArgs";
import { DeleteFileUploadArgs } from "./DeleteFileUploadArgs";
import { ProgressTrackerFindManyArgs } from "../../progressTracker/base/ProgressTrackerFindManyArgs";
import { ProgressTracker } from "../../progressTracker/base/ProgressTracker";
import { FileUploadService } from "../fileUpload.service";
@graphql.Resolver(() => FileUpload)
export class FileUploadResolverBase {
  constructor(protected readonly service: FileUploadService) {}

  async _fileUploadsMeta(
    @graphql.Args() args: FileUploadCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FileUpload])
  async fileUploads(
    @graphql.Args() args: FileUploadFindManyArgs
  ): Promise<FileUpload[]> {
    return this.service.fileUploads(args);
  }

  @graphql.Query(() => FileUpload, { nullable: true })
  async fileUpload(
    @graphql.Args() args: FileUploadFindUniqueArgs
  ): Promise<FileUpload | null> {
    const result = await this.service.fileUpload(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FileUpload)
  async createFileUpload(
    @graphql.Args() args: CreateFileUploadArgs
  ): Promise<FileUpload> {
    return await this.service.createFileUpload({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => FileUpload)
  async updateFileUpload(
    @graphql.Args() args: UpdateFileUploadArgs
  ): Promise<FileUpload | null> {
    try {
      return await this.service.updateFileUpload({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FileUpload)
  async deleteFileUpload(
    @graphql.Args() args: DeleteFileUploadArgs
  ): Promise<FileUpload | null> {
    try {
      return await this.service.deleteFileUpload(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [ProgressTracker], { name: "progressTrackers" })
  async findProgressTrackers(
    @graphql.Parent() parent: FileUpload,
    @graphql.Args() args: ProgressTrackerFindManyArgs
  ): Promise<ProgressTracker[]> {
    const results = await this.service.findProgressTrackers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
