/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsInt,
  Min,
  Max,
  IsOptional,
  ValidateNested,
  IsString,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { FileUpload } from "../../fileUpload/base/FileUpload";
import { EnumProgressTrackerProgressStatus } from "./EnumProgressTrackerProgressStatus";
import { EnumProgressTrackerStatus } from "./EnumProgressTrackerStatus";

@ObjectType()
class ProgressTracker {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  currentIndex!: number | null;

  @ApiProperty({
    required: false,
    type: () => FileUpload,
  })
  @ValidateNested()
  @Type(() => FileUpload)
  @IsOptional()
  fileUpload?: FileUpload | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    enum: EnumProgressTrackerProgressStatus,
  })
  @IsEnum(EnumProgressTrackerProgressStatus)
  @IsOptional()
  @Field(() => EnumProgressTrackerProgressStatus, {
    nullable: true,
  })
  progressStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumProgressTrackerStatus,
  })
  @IsEnum(EnumProgressTrackerStatus)
  @IsOptional()
  @Field(() => EnumProgressTrackerStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalItems!: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { ProgressTracker as ProgressTracker };
