/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SubCategoryService } from "../subCategory.service";
import { SubCategoryCreateInput } from "./SubCategoryCreateInput";
import { SubCategory } from "./SubCategory";
import { SubCategoryFindManyArgs } from "./SubCategoryFindManyArgs";
import { SubCategoryWhereUniqueInput } from "./SubCategoryWhereUniqueInput";
import { SubCategoryUpdateInput } from "./SubCategoryUpdateInput";
import { InventoryItemFindManyArgs } from "../../inventoryItem/base/InventoryItemFindManyArgs";
import { InventoryItem } from "../../inventoryItem/base/InventoryItem";
import { InventoryItemWhereUniqueInput } from "../../inventoryItem/base/InventoryItemWhereUniqueInput";

export class SubCategoryControllerBase {
  constructor(protected readonly service: SubCategoryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SubCategory })
  async createSubCategory(
    @common.Body() data: SubCategoryCreateInput
  ): Promise<SubCategory> {
    return await this.service.createSubCategory({
      data: {
        ...data,

        category: data.category
          ? {
              connect: data.category,
            }
          : undefined,
      },
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SubCategory] })
  @ApiNestedQuery(SubCategoryFindManyArgs)
  async subCategories(@common.Req() request: Request): Promise<SubCategory[]> {
    const args = plainToClass(SubCategoryFindManyArgs, request.query);
    return this.service.subCategories({
      ...args,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SubCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async subCategory(
    @common.Param() params: SubCategoryWhereUniqueInput
  ): Promise<SubCategory | null> {
    const result = await this.service.subCategory({
      where: params,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SubCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSubCategory(
    @common.Param() params: SubCategoryWhereUniqueInput,
    @common.Body() data: SubCategoryUpdateInput
  ): Promise<SubCategory | null> {
    try {
      return await this.service.updateSubCategory({
        where: params,
        data: {
          ...data,

          category: data.category
            ? {
                connect: data.category,
              }
            : undefined,
        },
        select: {
          category: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SubCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSubCategory(
    @common.Param() params: SubCategoryWhereUniqueInput
  ): Promise<SubCategory | null> {
    try {
      return await this.service.deleteSubCategory({
        where: params,
        select: {
          category: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/inventoryItems")
  @ApiNestedQuery(InventoryItemFindManyArgs)
  async findInventoryItems(
    @common.Req() request: Request,
    @common.Param() params: SubCategoryWhereUniqueInput
  ): Promise<InventoryItem[]> {
    const query = plainToClass(InventoryItemFindManyArgs, request.query);
    const results = await this.service.findInventoryItems(params.id, {
      ...query,
      select: {
        aprice: true,
        bcode: true,

        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        depart: true,
        descript: true,
        description: true,
        id: true,
        location: true,
        name: true,
        prodid: true,
        qtyonhand: true,

        subCategory: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/inventoryItems")
  async connectInventoryItems(
    @common.Param() params: SubCategoryWhereUniqueInput,
    @common.Body() body: InventoryItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventoryItems: {
        connect: body,
      },
    };
    await this.service.updateSubCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/inventoryItems")
  async updateInventoryItems(
    @common.Param() params: SubCategoryWhereUniqueInput,
    @common.Body() body: InventoryItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventoryItems: {
        set: body,
      },
    };
    await this.service.updateSubCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/inventoryItems")
  async disconnectInventoryItems(
    @common.Param() params: SubCategoryWhereUniqueInput,
    @common.Body() body: InventoryItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inventoryItems: {
        disconnect: body,
      },
    };
    await this.service.updateSubCategory({
      where: params,
      data,
      select: { id: true },
    });
  }
}
